# Generated by Django 5.1.1 on 2024-09-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_volunteer',
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('VOLUNTEER', 'Volunteer'), ('ADMIN', 'Admin')], default='VOLUNTEER', max_length=20),
        ),
    ]
