# Generated by Django 5.1.1 on 2024-09-19 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0003_alter_volunteer_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='availability',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='is_availabile',
            field=models.BooleanField(default=True),
        ),
    ]
